# Introduction to PyTorch
---

### About
Provide an introduction to PyTorch.

### Learning Objectives
- Explore the common deep learning toolkit PyTorch.

### Notebook Guide
- Imports
- What is a Tensor?
- How do Tensors Work?
    - Initializing a tensor
    - Tensor Attributes
    - Tensor Operations
    - Bridge with `numpy`
- Datasets and DataLoaders

**Note:** this lesson is designed to be run using Google Colab

# Imports

In [1]:
!pip install torch torchvision

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.6/526.6 MB 45.5 MB/s  0:00:07m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.2/366.2 MB 62.4 MB/s  0:00:04m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 MB 54.3 MB/s  0:00:03m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.0/206.0 MB 59.7 MB/s  0:00:03m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 70.4 MB/s  0:00:006m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.6/197.6 MB 55.7 MB/s  0:00:03m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 22.7 MB/s  0:00:006m0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 57.7 MB/s  0:00:05m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 34.5 MB/s  0:00:006m0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 MB 66.5 MB/s  0:00:016m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 54.2 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# What is a Tensor?
---

Tensors are very similar to arrays and matrices, we use them to encode the inputs and outputs of a model. For the most part, they will be similar to using `np.array`.

Why can't we use `np.array`?

Because Tensors are designed to run on hardware accelerators, like GPUs. When doing deep learning, it is likely that you'll have vast amounts of data, any techniques or data structures we can use to speed up our model training should be utilized.

# How do Tensors work?
---

## Initializing a tensor

In [ ]:
import torch
import numpy as np
#Start with some plan data - a python nested list
data = [[1, 2], [3, 4]]

#convert the data into a Pytorch tensor (the main data structure that we will use)
x_data = torch.tensor(data)

print(type(x_data))

---

In [9]:
# Can also be created from numpy arrays
np_array = np.array(data)
# use the .from_numpy function
x_np = torch.from_numpy(np_array)
print(type(np_array))
print(type(x_data))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


---

New tensors will retain the properties of the argument tensor unless overridden.

In [11]:
#ones_like copies the sahpe (and usually the dtype) of the argument,
#but fills every value with a 1. Handy when you want a matching "blank" tensor. 
x_ones = torch.ones_like(x_data)

x_ones

tensor([[1, 1],
        [1, 1]])

In [12]:
# overriding the data type of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float)

In [13]:
x_rand

tensor([[0.6141, 0.5480],
        [0.2760, 0.7751]])

---

`shape` is a tuple of tensor dimensions. It can be used to determine the dimensionality of the output tensor.

In [14]:
#share is a tupel: (rows, columns) 
shape = (2, 10,)

rand_tensor = torch.rand(shape)

rand_tensor

tensor([[0.5664, 0.4078, 0.4818, 0.5725, 0.3395, 0.8974, 0.2164, 0.7016, 0.3806,
         0.0494],
        [0.2479, 0.0379, 0.0260, 0.3427, 0.6750, 0.8045, 0.1993, 0.1101, 0.4020,
         0.8154]])

---

## Tensor Attributes

Attributes describe their shape, datatype, and device on which they are stored

In [15]:
#create a ramdpm 3x4 tensor of floats 
tensor = torch.rand(3, 4)

tensor

tensor([[0.2301, 0.9106, 0.4430, 0.0120],
        [0.2579, 0.1863, 0.5739, 0.6886],
        [0.1630, 0.2877, 0.3745, 0.3047]])

In [16]:
tensor.type

<function Tensor.type>

In [17]:
tensor.shape

torch.Size([3, 4])

In [18]:
tensor.dtype

torch.float32

In [20]:
tensor.device

device(type='cpu')

---

## Tensor Operations

As mentioned before, tensor operations will feel similar to `numpy`. Below we see how to index and slice.

In [22]:
#start with a 4x4 tensor filled with ones
tensor = torch.ones(4, 4)
#indexing/slicing works like numpy:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
#set the entire second colmn to 0 (column index 1)
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


You can concatenate a sequence of tensors along a specified dimension with `torch.cat`.

We'll use the `tensor` defined in the previous cell to illustrate.

In [23]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)

t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

---

Arithmetic Operations

In [24]:
# Matric multiplications with @ operator
#tenosr.T is the transpose ( rows become columns), needed for valid matmul shape]
y1 = tensor @ tensor.T

y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [25]:
y2 = tensor.matmul(tensor.T)

y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [26]:
y3 = torch.rand_like(y1)

torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [27]:
# Computes element-wise product. z1, z2, z3 will have same value

In [30]:
#computes element-wise pruduct. z1, z2, z3 will have same value
z1 = tensor * tensor

z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [29]:
#same element -wise product as *, written as a mehto. result matches Z1
z2 = tensor.mul(tensor)
#Identical 
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

---

## Bridge with `numpy`

In [31]:
#create a 1D tensor of 5 ones, then convert to a numpy
t = torch.ones(5)

t


tensor([1., 1., 1., 1., 1.])

In [33]:
#convert the tensor to the numpy array
n = t.numpy()

print(n)
print('='*30)
print(f'n is type: {type(n)} \nand t is {type(t)}')

[1. 1. 1. 1. 1.]
n is type: <class 'numpy.ndarray'> 
and t is <class 'torch.Tensor'>


In [34]:
t.add_(1)

print(f"t: {t}")
print(f"n: {n}")

# a change in the tensor being reflected in numpy

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [37]:
# From numpy back to a tensor

n = np.ones(5)
t = torch.from_numpy(n)

In [38]:
# similar process to before
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


# Datasets and DataLoaders
---

Data cleaning and processing is going to be the bulk of our work.

PyTorch provides two data primitives `torch.utils.data.DataLoader` and `torch.utils.data.Dataset`. We can use pre-loaded data sets and our own data.

What is the difference?

* `Dataset` stores the samples and their corresponding labels.
* `DataLoader` wraps an iterable around the `Dataset` to enable access to the samples.

We'll see an example with the [Fashion-MNIST](https://research.zalando.com/project/fashion_mnist/fashion_mnist/) data set.

In [44]:
#Dataset : base class for custom data sets
#datasets: buil-in datasets lik FashionMinst
#toTensor: Turns images into tensors and scales the pixel valume
#matplotlib for plotting images if we want to inspect them

import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor # converts PIL image or np.array to a tensor and scales values
import matplotlib.pyplot as plt



In [50]:
#load the fashionMinst training set. 
#root:folder to store files
#train=True use the training split
#download=True download if the dataset isn't already on disk
#transform=toTensor() convert each image to a tensor before we use if
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

In [52]:
#same dataset, but train=false gives us the held-out test images.
#we keep train and test seperate so we can check generalization later. 

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

---

Trying an example with a dummy data set.

In [54]:
# First we need to set up a class that inherists from Dataset
#custom dataset clas that unherits from pytorch dataset. 
#dataloader expects these special methods so it can batch out data
class MyDataset(Dataset):
    #store the features (dat0 and targets (labels on the object)
    
  def __init__(self, data, labels):
    self.data = data
    self.labels = labels
#returns the length of the data set (print how many samples there are)
    #dataloader uses this for batching
  def __len__(self):
    return len(self.data)

    #return one sample for a given index (idx)
    #dataloader calls this repeatedly to build each batch
  def __getitem__(self, idx):
    x = self.data[idx]
    y = self.labels[idx]

    return x, y

---

Let's breakdown what's happening in our `MyDataset` class.

`Dataset` is an abstract base class. We need PyTorch to have two special methods, `__len__` and `__getitem__`.

The `__len__` method returns the size of the dataset (duh!). But why do we need that? The `DataLoader` uses this method to determine how many batches to make and when to start an epoch!

The `__getitem__` method fetches one sample, usually a feature and a label, from a given index (our `idx` argument). The `DataLoader` calls this to build batches for training.

The `DataLoader` uses our `DataSet` to make our model training more efficient!

---

So why can't we simply convert our dataset to a `tensor` and then throw it at `DataLoader`?

When we're working with *real* data out in the wild, we're likely to have lots of data than can't fit in memory. We'll need to preprocess and transform data on the fly. The `Dataset` gives you the power to define custom fetching logic and transformations.

## *Big Picture*

Big O notation and algorithmic complexity become important in deep learning. A good thing to keep in the back of your mind as a data scientist is how does your solution scale for more data. By wrapping our `Dataset` into the `DataLoader`, we're going to have an efficient and scalable pipeline. We're rarely going to have a dataset that will be a simple list or tensor that we'll pass through a model.

In [59]:
# Let's make some dummy data to show how we go from Dataset -> DataLoader
#Tne fake dataset so we can see Dataset -> dataloader clearly
data = torch.arange(10)
labels = torch.arange(10)*2
#wrap the tensors in our custom dataset class
dataset = MyDataset(data, labels)

In [60]:
from torch.utils.data import DataLoader

In [65]:
# We made a data set with our MyDataset class! Now wrap in DataLoader
dataloader = DataLoader(
    dataset,
    batch_size=2, # how many samples per epoch
    shuffle = True, # shuffle data every epoch
    num_workers=0, # no extra workers, everything runs in the main process.
)

In [66]:
# Iterate through batches to see the dataloader in action!
for batch_idx, (x, y) in enumerate(dataloader):
  print(f"Batch index: {batch_idx}")
  print(f"Data: {x}")
  print(f"Label: {y}")
  print()

Batch index: 0
Data: tensor([7, 5])
Label: tensor([14, 10])

Batch index: 1
Data: tensor([6, 8])
Label: tensor([12, 16])

Batch index: 2
Data: tensor([0, 9])
Label: tensor([ 0, 18])

Batch index: 3
Data: tensor([2, 3])
Label: tensor([4, 6])

Batch index: 4
Data: tensor([1, 4])
Label: tensor([2, 8])

